# Generated by Django 4.2.3 on 2023-08-01 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='submission_type',
            new_name='type_of_submission',
        ),
    ]
