# Generated by Django 4.2.3 on 2023-08-01 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_submission_type_hackathon_type_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_hackathons', to=settings.AUTH_USER_MODEL),
        ),
    ]
